name: widgetbook-demo
repository: https://github.com/widgetbook/widgetbook-demo

packages:
  - packages/**
  - app_widgetbook/**
  - '*'

command:
  version:
    branch: main
    workspaceChangelog: true