name: Build 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Build Website
        run: flutter build web -t app_widgetbook/lib/main.dart

      - name: Upload Widgetbook
        uses: widgetbook/widgetbook-hosting@0.0.24
        with:
          path: 'build/web'
          api_key: 'iL9RQkaGdb3VjLonSu0wb4xlFEKHfErO'
