name: Build
on:
  push:
    branches:
      - staging
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get dependencies
        working-directory: ./app_widgetbook
        run: flutter pub get

      - name: Build Website
        working-directory: ./app_widgetbook
        run: flutter build web -t lib/main.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        working-directory: ./app_widgetbook
        run: |
          widgetbook \
                --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} \
                --repository \
                $GITHUB_REPOSITORY \
                --actor \
                $GITHUB_ACTOR
